services:
  facilito-backend:
    build: .
    container_name: facilito-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=crm
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    restart: always
    networks:
      - facilito-network

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - facilito-network

networks:
  facilito-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
