spring.application.name=facilito-crm
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?prepareThreshold=0}
spring.datasource.username=${DB_USER:postgres.nrexuvargblspsnrpkld}
spring.datasource.password=${DB_PASS:Chbmkt#2024}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=crm

# Configuração para HTTPS (Cloudflare Proxy)
server.forward-headers-strategy=native
spring.datasource.hikari.maximum-pool-size=2

