spring.application.name=facilito-crm
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.nrexuvargblspsnrpkld
spring.datasource.password=Chbmkt#2024
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=crm

# Se você criou um schema específico (ex: 'crm'), descomente a linha abaixo e coloque o nome:
# spring.jpa.properties.hibernate.default_schema=NOME_DO_SCHEMA
